- hosts: all
  become: true
  roles:
    - common

# - hosts: control_plane
#   become: true
#   roles:
#     - kubeadm

# - hosts: control_plane
#   become: true
#   roles:
#     - cni-calico
#     - metrics-server
#     - node-labels
